### ISSUE TITLE
Error when running example

### ISSUE THREAD

**Issue by sergiolombrico** [RealKinetic/elm-firestore#18]
When running the example I get the following error:

Error: Compilation failed
Compiling ...-- NAMING ERROR --------------------------------------------------- src/Main.elm

I cannot find a `Firestore.Sub.ChangeType` type:

492| handleChange : Model -> Firestore.Sub.ChangeType -> Firestore.Document.Document -> Cmd Msg
                             ^^^^^^^^^^^^^^^^^^^^^^^^

Could you help me to get this running?

Thank you.

S.

**Comment by cmditch** [comment]
I updated the example to the latest API. Sorry about the delay :\

One will still have to plug their own firebase project config in to get things working.
